[package]
name = "api"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tower_governor = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
uuid = { workspace = true }
aes-gcm = { workspace = true }
base64 = { workspace = true }
rand = { workspace = true }
argon2 = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
email_address = { workspace = true }
unicode-normalization = { workspace = true }
jsonwebtoken = { workspace = true }
tokio-cron-scheduler = { workspace = true }
lettre = { workspace = true }

domain = { workspace = true }
db = { workspace = true }
plaid = { workspace = true }
broker = { workspace = true }

[dev-dependencies]
tower = { workspace = true }
rust_decimal_macros = { workspace = true }
async-trait = { workspace = true }
